### ISSUE TITLE
master/code/dist/readme.txt ... some bagatelles.

### ISSUE THREAD

**Issue by drawkula** [SmallRoomLabs/cpm8266#17]
[master/code/dist/readme.txt#L6](https://github.com/SmallRoomLabs/cpm8266/blob/master/code/dist/readme.txt#L6) ... current version is not started via EMON.

[master/code/dist/readme.txt#L25-L29](https://github.com/SmallRoomLabs/cpm8266/blob/master/code/dist/readme.txt#L25-L29) ... still refers to `cpm8266_01.bin`.

[master/code/dist/readme.txt#L48](https://github.com/SmallRoomLabs/cpm8266/blob/master/code/dist/readme.txt#L48) ... now mention the autobauder?

[master/code/dist/readme.txt#L61-L72](https://github.com/SmallRoomLabs/cpm8266/blob/master/code/dist/readme.txt#L61-L72) ... "screenshot" is from `cpm8266_01.bin`, so still shows `EMON` and "cpm8266 v0.1" as startup message.

**Comment by SmallRoomLabs** [comment]
Nice catches!  I'll take care of those bugmissions tonight.....

**Comment by drawkula** [comment]
Now there are `cpm8266_VERSION.bin` and `cpm8266_04.bin` in the text.

I thought you would change every `cpm8266_01.bin` to `cpm8266_VERSION.bin`, so I did not mention the places where `cpm8266_VERSION.bin` was used...

Sorry... :-(
