### ISSUE TITLE
conflict in headers

### ISSUE THREAD

**Issue by aldolo69** [SmallRoomLabs/cpm8266#22]
[CC] main.c
In file included from main.c:3:0:
espincludes.h:39:6: error: conflicting types for 'ets_isr_attach'
 void ets_isr_attach(int intr, void *handler, void *arg);
      ^
In file included from /home/aldo/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/os_type.h:28:0,
                 from main.c:2:
/home/aldo/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:67:6: note: previous declaration of 'ets_isr_attach' was here
 void ets_isr_attach(int i, ets_isr_t func, void *arg);
      ^
Makefile:109: set di istruzioni per l'obiettivo "main.o" non riuscito
make: *** [main.o] Errore 1

maybe there was an update in the sdk??

**Comment by aldolo69** [comment]
I've commented out in espincludes.h the line with the ets_isr_attach declaration. Now "make" works

**Comment by drawkula** [comment]
Why did you close this?  
Is it fixed?  
Did it turn out to be not neccessary?

**Comment by drawkula** [comment]
Related: Issue https://github.com/SmallRoomLabs/cpm8266/issues/21.

**Comment by aldolo69** [comment]
i'm restarting from scratch because of inconsistencies changing the esp8266 board. incidentally a 1m board was able to return something, while a 4m one does not produce any output in the console. i'm going to do some experiments to gain more feeling with this kind of projects.

anyway YES, even in the second attempt i've commented out the line in espincludes.h to complete the make process, but the result was not encouraging after the upload.
